name:                ShantyBot
version:             0.1.0.0
github:              nomicflux/shantybot
license:             MIT
author:              Michael Anderson
maintainer:          nomicflux@gmail.com
copyright:           2017 Michael Anderson

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/shantybot#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - base
  - text
  - aeson
  - bytestring
  - cryptohash
  - time
  - http-types
  - byteable
  - string-random
  - case-insensitive
  - http-client
  - pipes
  - pipes-http
  - pipes-bytestring
  - pipes-aeson
  - base64-bytestring
  - transformers
  - yaml

executables:
  ShantyBot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ShantyBot

tests:
  ShantyBot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ShantyBot
    - hspec
    - QuickCheck
    - bytestring
